### PR TITLE
Implement Plus node adder

### PR DESCRIPTION
**Pull request by serebit**
I found a shader in https://github.com/ovlack/apex-info that seems to render more accurately compared to Cores 1.3, and has inputs that better match the textures that Apex models ship with. This PR implements that shader.

The following is a comparison between Loba auto-shaded with this PR, and Loba auto-shaded with the main branch. Note the weird shading on the skin on her face and chest.

## Loba (this PR)

loba-plus

## Loba (main)

loba-cores

### CODE REVIEW

**Comment by Kaiserouo** [comment]
This indeed looks a bit nicer, but I may have to check how it holds up for other models later.

Also I'm thinking whether it is necessary to maintain 2 versions of NodeAdder etc. to support both Cores and Plus, since, after all, I don't have reason to assume they are the original author of the Plus shader, and I think Cores may still be the most popular one (at least it's got quite a few tutorials). Might as well keep the original functionality in place...

I might also refactor and relocate some code to other files, so I probably won't just accept the PR...? This is literally the first time I got a PR so not really knowing what I'm doing here. I'll see what I can do when I have time.

**Comment by serebit** [comment]
All good. Looking at the two renders again, her hair looks more accurate with Cores, so it's probably worth keeping both just in case.

As for other models, I gave both a try with the Flatline and Volt, and both looked far better and more game-accurate with the Plus shader. I would definitely recommend trying other character models though.

Also, as an aside, technically any PRs are illegal because you haven't attached a license to the repository. If you don't explicitly put it under an open-source license, the code is copyrighted with all rights reserved. I'd recommend looking at https://choosealicense.com/, picking the one you like, and just adding it as a LICENSE file to the top level of the repo.

**Comment by Kaiserouo** [comment]
After a bit of testing, I think there is a need for both to coexist.  Some things I found as follows:
+ Opacity multiplier for Plus only works in Cycle, but in Cores both Eevee and Cycles works. (e.g. `pilot_light_wraith`'s `suit`, `pilot_medium_bloodhound_old_ways`'s `gear`). So for some skins in Eevee, Cores is the only viable option.
+  `pilot_medium_stim`'s skin in Plus is normal skin color, but in Cores it's orange due to `scatterThicknessTexture`.
+ `pilot_medium_bloodhound`'s fur in Plus is whiter (as it should have), but in Cores it's greyer.
+ Plus seems to be slower? did not rigorously tested it, just gut feelings.
+ `pilot_medium_fuse`'s hair is still white for both shader, due to `specTexture`.
+ `pilot_medium_fuse`'s nose's subsurface scattering is a bit overwelming (at least by default).
    + 
+ `bloodhound_v21_pilot_level03`'s style have huge difference. (Uses Cycles. Left is Plus, right is Cores. Personally I like Cores' version.)
    + 

So Plus is good for Cycles and almost all cases, even some where Cores fails (e.g. Octane). But Cores have different style on some characters (e.g. Apex Hunter) and opacity multiplier works even for Eevee.

I might make a menu s.t. people could select what "mode" they want to use, instead of choosing existing blender files (the node inteface will very likely be different anyways so why have this option). That way people can use different shader for each character (or even each mesh) without much trouble. I probably couldn't accept this PR but if you'd like, you can contribute about the Plus part later when I'm done with that...

...or I can also deal with that along with everything else. The commit won't have your name though so that's quite a problem.

**Comment by serebit** [comment]
I could also just PR the additional blend file and some related constants in the Python code as a minimum. The work in this PR doesn't need to be merged, it can just serve as a point to start from with your implementation :)

**Comment by Kaiserouo** [comment]
I have implemented the code refactor and the menu, as well as the README description. If you wish, you can implement `PlusNodeAdder` in `node_adder.py` by the interface `NodeAdder` and things should work fine. If you don't have time, you can leave a comment here and I will implement those another day with the changes in this PR.

Please note that the asset's blend file in the main branch also contain `Pathfinder Emote UV Transform Node`, so do not delete or change that file.

**Pull request merged**
